#!/bin/bash

# DWG Block Extractor Build Script
# Generate standalone executables using PyInstaller
# Execute from project root
# Follows working directory convention: uses root-relative paths, no cd commands

set -e  # Exit on error

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
APP_NAME="DWGBlockExtractor"
APP_VERSION="0.1.0"
VERBOSE=0
PRESERVE_ARTIFACTS=0

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -v|--verbose)
            VERBOSE=1
            shift
            ;;
        -p|--preserve)
            PRESERVE_ARTIFACTS=1
            shift
            ;;
        -h|--help)
            echo "DWG Block Extractor Build Script"
            echo ""
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  -v, --verbose    Show detailed build output"
            echo "  -p, --preserve   Preserve build artifacts (build/, *.spec)"
            echo "  -h, --help       Display this help message"
            echo ""
            echo "Output:"
            echo "  - Executable will be created in dist/ directory"
            echo "  - Platform: $(uname -s)"
            exit 0
            ;;
        *)
            echo -e "${RED}Error: Unknown option: $1${NC}"
            echo "Use -h or --help for usage information"
            exit 1
            ;;
    esac
done

# Function to log verbose messages
log_verbose() {
    if [ $VERBOSE -eq 1 ]; then
        echo -e "${BLUE}[VERBOSE]${NC} $1"
    fi
}

# Function to check uv installation
check_uv() {
    log_verbose "Checking for uv package manager..."

    if ! command -v uv &> /dev/null; then
        echo -e "${RED}Error: uv package manager not found${NC}"
        echo ""
        echo "Please install uv by running:"
        echo -e "${GREEN}curl -LsSf https://astral.sh/uv/install.sh | sh${NC}"
        exit 1
    fi

    log_verbose "Found uv: $(uv --version 2>&1)"
}

# Function to install build dependencies
install_build_deps() {
    echo -e "${BLUE}Installing build dependencies...${NC}"
    log_verbose "Installing pyinstaller from build group..."

    # Install build dependencies using uv
    uv pip install --group build || {
        echo -e "${RED}Error: Failed to install build dependencies${NC}"
        echo "Please ensure pyproject.toml has build group configured"
        exit 1
    }

    echo -e "${GREEN}Build dependencies installed successfully${NC}"
}

# Function to detect platform and set executable extension
detect_platform() {
    PLATFORM=$(uname -s)
    log_verbose "Detected platform: $PLATFORM"

    case "$PLATFORM" in
        MINGW*|MSYS*|CYGWIN*|Windows_NT)
            PLATFORM_NAME="Windows"
            EXE_EXT=".exe"
            ;;
        Linux)
            PLATFORM_NAME="Linux"
            EXE_EXT=""
            ;;
        Darwin)
            PLATFORM_NAME="macOS"
            EXE_EXT=""
            ;;
        *)
            echo -e "${YELLOW}Warning: Unknown platform: $PLATFORM${NC}"
            PLATFORM_NAME="Unknown"
            EXE_EXT=""
            ;;
    esac

    log_verbose "Platform: $PLATFORM_NAME, Extension: ${EXE_EXT:-none}"
}

# Function to create PyInstaller spec file
create_spec_file() {
    log_verbose "Creating PyInstaller spec file..."

    SPEC_FILE="${APP_NAME}.spec"

    cat > "$SPEC_FILE" << 'EOF'
# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec file for DWG Block Extractor
Generated by build.sh
"""

import os
import sys
from pathlib import Path

# Add app directory to path for imports
sys.path.insert(0, str(Path.cwd() / 'app'))

block_cipher = None

a = Analysis(
    ['app/main.py'],
    pathex=[],
    binaries=[],
    datas=[
        # Include customtkinter theme files
        ('$(uv run python -c "import customtkinter; import os; print(os.path.dirname(customtkinter.__file__))")', 'customtkinter'),
    ],
    hiddenimports=[
        'customtkinter',
        'ezdxf',
        'ezdxf.addons',
        'ezdxf.addons.drawing',
        'pandas',
        'openpyxl',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='DWGBlockExtractor',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # No console window for GUI app
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
EOF

    # Fix the customtkinter path in the spec file
    CTK_PATH=$(uv run python -c "import customtkinter; import os; print(os.path.dirname(customtkinter.__file__))" 2>/dev/null || echo "")

    if [ -n "$CTK_PATH" ]; then
        log_verbose "CustomTkinter path: $CTK_PATH"
        # Replace the command with actual path in spec file
        sed -i.bak "s|('.*customtkinter.*')|('$CTK_PATH', 'customtkinter')|g" "$SPEC_FILE" 2>/dev/null || \
        sed -i "s|('.*customtkinter.*')|('$CTK_PATH', 'customtkinter')|g" "$SPEC_FILE"
        rm -f "${SPEC_FILE}.bak"
    else
        echo -e "${YELLOW}Warning: Could not detect customtkinter path${NC}"
    fi

    log_verbose "Spec file created: $SPEC_FILE"
}

# Function to run PyInstaller
run_pyinstaller() {
    echo -e "${BLUE}Building executable...${NC}"
    log_verbose "Running PyInstaller with spec file..."

    SPEC_FILE="${APP_NAME}.spec"

    if [ $VERBOSE -eq 1 ]; then
        uv run pyinstaller "$SPEC_FILE" --clean --noconfirm
    else
        uv run pyinstaller "$SPEC_FILE" --clean --noconfirm > /dev/null 2>&1 || {
            echo -e "${RED}Error: PyInstaller build failed${NC}"
            echo "Run with -v flag for detailed output"
            exit 1
        }
    fi

    echo -e "${GREEN}Build completed successfully${NC}"
}

# Function to verify build output
verify_build() {
    log_verbose "Verifying build output..."

    EXPECTED_EXE="dist/${APP_NAME}${EXE_EXT}"

    if [ -f "$EXPECTED_EXE" ]; then
        FILE_SIZE=$(du -h "$EXPECTED_EXE" | cut -f1)
        echo -e "${GREEN}Executable created: $EXPECTED_EXE ($FILE_SIZE)${NC}"

        if [ $VERBOSE -eq 1 ]; then
            echo ""
            echo -e "${BLUE}Build artifacts:${NC}"
            ls -lh "dist/"
        fi

        return 0
    else
        echo -e "${RED}Error: Expected executable not found: $EXPECTED_EXE${NC}"
        return 1
    fi
}

# Function to cleanup build artifacts
cleanup_artifacts() {
    if [ $PRESERVE_ARTIFACTS -eq 0 ]; then
        log_verbose "Cleaning up build artifacts..."

        # Remove build directory
        if [ -d "build" ]; then
            rm -rf build
            log_verbose "Removed build/"
        fi

        # Remove spec file
        if [ -f "${APP_NAME}.spec" ]; then
            rm -f "${APP_NAME}.spec"
            log_verbose "Removed ${APP_NAME}.spec"
        fi

        echo -e "${GREEN}Build artifacts cleaned up${NC}"
    else
        log_verbose "Preserving build artifacts (--preserve flag set)"
        echo -e "${YELLOW}Build artifacts preserved in build/ and ${APP_NAME}.spec${NC}"
    fi
}

# Function to show build summary
show_summary() {
    echo ""
    echo -e "${BLUE}=== Build Summary ===${NC}"
    echo "Application: $APP_NAME"
    echo "Version: $APP_VERSION"
    echo "Platform: $PLATFORM_NAME"
    echo "Executable: dist/${APP_NAME}${EXE_EXT}"
    echo ""
    echo "To run the executable:"
    echo -e "${GREEN}./dist/${APP_NAME}${EXE_EXT}${NC}"
    echo -e "${BLUE}=====================${NC}"
}

# Main execution
main() {
    echo -e "${BLUE}DWG Block Extractor - Build Script${NC}"
    echo ""

    # Run checks
    check_uv
    detect_platform

    # Install dependencies
    install_build_deps

    # Create spec file
    create_spec_file

    # Build executable
    run_pyinstaller

    # Verify build
    verify_build || {
        echo -e "${RED}Build verification failed${NC}"
        exit 1
    }

    # Cleanup
    cleanup_artifacts

    # Show summary
    show_summary
}

# Run main function
main
